### ISSUE TITLE
Option to remove all duplicates

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [hi5/TF#12]
Currently TF_RemoveDuplicateLines only removes the additional duplicates, so 1 of the duplicate is always left behind. Could an option be added to remove all instances of the duplicate so none of them show? This would be useful for comparing 2 lists when you only want to see the non-duplicate items.

**Comment by hi5** [comment]
You can try this - add/insert this to tf.ahk (at the end of the file for example) 

Call it by using `2` for the `Consecutive` parameter to have it remove duplicate lines:
`TF_RemoveDuplicateLines2("File.txt", , , 2)`

```autohotkey
TF_RemoveDuplicateLines2(Text, StartLine = 1, Endline = 0, Consecutive = 0, CaseSensitive = false)
	{
	 TF_GetData(OW, Text, FileName)
	 If (StartLine = "")
		StartLine = 1
	 If (Endline = 0 OR Endline = "")
		EndLine := TF_Count(Text, "`n") + 1
	 Loop, Parse, Text, `n, `r
		{
		 If (A_Index < StartLine)
			Section1 .= A_LoopField "`n"
		 If A_Index between %StartLine% and %Endline%
			{
			 If (Consecutive = 1)
				{
				 If (A_LoopField <> PreviousLine) ; method one for consecutive duplicate lines
					 Section2 .= A_LoopField "`n"
				 PreviousLine:=A_LoopField
				}
			 Else
				{
				 If !(InStr(SearchForSection2,"__bol__" . A_LoopField . "__eol__",CaseSensitive)) ; not found
					{
					 SearchForSection2 .= "__bol__" A_LoopField "__eol__" ; this makes it unique otherwise it could be a partial match
					 Section2 .= A_LoopField "`n"
					}
				 else
					dupes .= A_LoopField "`n"
				}
			}
		 If (A_Index > EndLine)
			Section3 .= A_LoopField "`n"
		}
	 If (Consecutive = 2)
		Loop, parse, dupes, `n, `r
			section2:=StrReplace(section2,A_LoopField "`n","`n")
	 Output .= Section1 Section2 Section3
	 Return TF_ReturnOutPut(OW, OutPut, FileName)
	}
```

**Comment by asdsadsaasd12312132** [comment]
Could I just replace the TF_RemoveDuplicateLines function in tf.ahk with the code from TF_RemoveDuplicateLines2? Would everything be backwards compatible after? Incidentally, TF_RemoveDuplicateLines2 works.

**Comment by hi5** [comment]
You could do that or leave it as is e.g. simply use `TF_RemoveDuplicateLines2()` that way you have `TF_RemoveDuplicateLines()` to fall back to if something does go wrong at some point - I have only briefly tested it, so there might be unexpected results at some point. 

I don't want to change too much to TF - apart from obvious errors - as scripts that I (and perhaps others) use it for expect certain results, and I don't want to risk introducing changes that would require me to rewrite/retest code that I've been running for years.
