### ISSUE TITLE
using TF_ReplaceInLines and pointing it at users AppData folder

### ISSUE THREAD

**Issue by BeardyMike** [hi5/TF#13]
In "myfile.xml", I want to replace FALSE with TRUE on Line 1, so I used your library as follows:
 TF_ReplaceInLines("!%A_AppData%\Roaming\myfile.xml""1","","False","True")

This does not work for me. The value is not changed.

If I put in the full file address like this:
TF_ReplaceInLines("!C:\Users\USERNAME\Roaming\myfile.xml""1","","False","True") it works.

Is there a way to get this function working with %AppData% or %A_AppData% as I will be distributing this file to my family, and I dont know their USERNAMEs.

Thanks in advance.

**Comment by hi5** [comment]
Try `TF_ReplaceInLines("!" A_AppData "\Roaming\myfile.xml""1","","False","True")`

**Comment by BeardyMike** [comment]
We both missed a comma after the file location, but yes you did get it working for me.

`TF_ReplaceInLines("!" A_AppData "\myfile.xml","1","1","False","True")`

Thanks for your help.
