### ISSUE TITLE
Lots of functions not working

### ISSUE THREAD

**Issue by yogalD** [hi5/TF#3]
I don't understand why but functions like TF_LineNumber aren't working, as in, they do absolutely nothing. If I have a sample file with a bunch of lines (around 45 lines) of "asdf", called File.txt, and I copy and paste the example line:
`TF_LineNumber("File.txt",1,15,A_Space)`
Nothing happens to the file - the file is not changed at all. And this is copied from the example so there is absolutely no way I could have messed it up.
It's not a permission issue either, since I can write to the file with normal AHK code.

**Comment by hi5** [comment]
yogalD wrote
> Nothing happens to the file - the file is not changed at all.

That is actually correct when you use it as you indicate `TF_LineNumber("File.txt",1,15,A_Space)`

What this does is create a **new** text file called `File_Copy.txt` - it is explained in https://github.com/hi5/TF#quick-intro-to-parameters 

> If Text starts with **!** (eg: "!c:\sample.txt") it will **overwrite** the text file, otherwise it will save the **new** file to a copy of the text file eg: Filename**_copy**.txt

This is done for safety so people must actually indicate they wish to overwrite / update the original. So you can make it work (as you want) by adding a ! infront of the filename `TF_LineNumber("!File.txt",1,15,A_Space)`

I hope this is explains it and it now works for you as well.

**Comment by yogalD** [comment]
Thank you, I somehow missed that seeing as the readme is so huge.
If my tone came off as a bit rude, my apologies as I was in a bit of a rush when I wrote that. Although I am curious as to why this is the case as it's unlikely anyone would use these commands without the intention of actually editing the target file.

**Comment by hi5** [comment]
No worries. It is a common question, perhaps I should make it appear red and bold at the very top :smile: 
Because it is easy to make a mistake I made it so you can just test it out first before adding the !, better safe than sorry. (and I didn't want to add an additional parameter for the output file so the ! seemed logical at the time)
