### ISSUE TITLE
Error at line 151 in #include file

### ISSUE THREAD

**Issue by philibeur** [hi5/TF#8]
Error at line 151 in #include file
"C:\Sysinternal\AutoHotkey\Library\TF\tf.ahk"

Line Text:
data-hydro-click="{&quot;event_type&quot;:&quot;authentication.click&quot;,&quot;payload&quot;:{&quot;location_in_page&quot;:&quot;site header&quot;,&quot;repository_id&quot;:null,&quot;auth_type&quot;:&quot;SIGN_UP&quot;,&quot;originating_url&quot;:&quot;https://github.com/hi5/TF/blob/master/tf.ahk&quot;,&quot;user_id&quot;:null}}" data-hydro-click-hmac="9bfa7217bce64129a14fd6cd3fec393f409275859f7468c3ec0b29ca2aa0588c"

Error: This line does not contain a recognized action.

The program will exit.

**Comment by hi5** [comment]
Looks like you download the webpage displaying tf.ahk and not tf.ahk itself.

You can download it as a ZIP file if you press the green CODE button on the TF repository here https://github.com/hi5/TF (top right somewhere) should give you this link https://github.com/hi5/TF/archive/master.zip (and tf.ahk is in that zip file)

Or you press the RAW button when you view the tf.ahk "page" on Gitihub which goes to https://raw.githubusercontent.com/hi5/TF/master/tf.ahk which you can directly save from your browser.

Hope this helps.

**Comment by philibeur** [comment]
Ok, so much for me, thank you very much.
