### ISSUE TITLE
$ doesn't work in TF_RegExReplace 

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [hi5/TF#9]
I have uploaded the ahk and txt file I using. It seems to be unable to detect .mp3 when I include $.
[Test.zip](https://github.com/hi5/TF/files/5674648/Test.zip)

**Comment by asdsadsaasd12312132** [comment]
I am not sure if it is intended or not but it seems this is caused by TF_RegExReplace treating the entire file as 1 line, so there only exists one start (^) and one end ($). Using TF_RegExReplaceInLines("Music.txt", 1, 0, " - \d+$","") solved the issue for me.

**Comment by hi5** [comment]
I think you are missing the "m)" option - Multiline - https://www.autohotkey.com/docs/misc/RegEx-QuickRef.htm
 
```autohotkey
#Include tf.ahk
TF_RegExReplace("Music.txt","\.mp3\$","d")  ; this will do nothing as escaping $ as endline character means it looks for a literal $ sign
TF_RegExReplace("Music.txt","\.mp3$","d")   ; this will only operate on the very last lnie
TF_RegExReplace("Music.txt","m)\.mp3$","d") ; this probably does what you want due to the m) option
```

**Comment by asdsadsaasd12312132** [comment]
Solved.
